### ISSUE TITLE
Tests Fail on Master

### ISSUE THREAD

**Issue by pcwinters** [mikestaub/serverless-express#14]
Tests are currently failing on master.

```
$ git clone https://github.com/mikestaub/serverless-express.git
Cloning into 'serverless-express'...
remote: Enumerating objects: 1442, done.
remote: Total 1442 (delta 0), reused 0 (delta 0), pack-reused 1442
Receiving objects: 100% (1442/1442), 839.05 KiB | 419.00 KiB/s, done.
Resolving deltas: 100% (532/532), done.
$ cd serverless-express/
$ node --version
v8.14.0
$ npm --version
6.4.1
$ npm install

> fsevents@1.1.3 install /private/tmp/serverless-express/node_modules/fsevents
> node install

[fsevents] Success: "/private/tmp/serverless-express/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 637 packages from 689 contributors and audited 8254 packages in 27.232s
found 155 vulnerabilities (60 low, 75 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm run test

> serverless-express@2.0.8 test /private/tmp/serverless-express
> jest --verbose

 FAIL  test/plugin.test.js
  serverless-express plugin
    ✓ should call initialize method when the plugin gets instantiated (5ms)
    ✓ should initialize the plugin in the right sequence (1ms)
    ✓ should throw an error if the provider is not  supported yet (1ms)
    ✓ should not throw an error if provider is supported (1ms)
    ✕ should set providerName as environment variable when it's a supported provider (240ms)
    ✕ should create serverless environment object if it's undefined

  ● serverless-express plugin › should set providerName as environment variable when it's a supported provider

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at tdd.supported_providers.forEach.providerName (test/plugin.test.js:77:20)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/plugin.test.js:76:29)

  ● serverless-express plugin › should create serverless environment object if it's undefined

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at Object.<anonymous> (test/plugin.test.js:95:18)

 FAIL  test/express.test.js
  serverless-express express
    ✓ should let the user import module through require('serverless-express/express') (1ms)
    ✓ should expose an API that is exaclty what express app exposes (3ms)
    ✓ should expose an API that is exaclty what express exposes
    ✕ should implement aws-serverless-express middleware on aws-lambda only (2ms)
    ✕ should set header Access-Control-Allow-Origin to * by default

  ● serverless-express express › should implement aws-serverless-express middleware on aws-lambda only

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at tdd.supported_providers.forEach.provider (test/express.test.js:67:7)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/express.test.js:65:29)

  ● serverless-express express › should set header Access-Control-Allow-Origin to * by default

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at tdd.supported_providers.forEach.provider (test/express.test.js:86:7)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/express.test.js:84:29)

 FAIL  test/handler.test.js
  serverless-express handler
    ✓ should let the user import module through require('serverless-express/handle')
    ✕ should handle express correctly with aws (2ms)
    ✕ should handle express correctly with google
    ✕ should handle express correctly with azure
    ✓ should throw error if a handler is used inside not-supported provider (1ms)

  ● serverless-express handler › should handle express correctly with aws

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at Object.<anonymous> (test/handler.test.js:26:7)

  ● serverless-express handler › should handle express correctly with google

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at Object.<anonymous> (test/handler.test.js:26:7)

  ● serverless-express handler › should handle express correctly with azure

    TypeError: sls_express is not a constructor

      14 |
      15 |
    > 16 |     return new sls_express(serverless, plugin_options)
      17 | }
      18 |

      at Object.<anonymous>.module.exports (test/src/init-plugin.js:16:12)
      at Object.<anonymous> (test/handler.test.js:26:7)

------------------------------|----------|----------|----------|----------|----------------|
File                          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------------|----------|----------|----------|----------|----------------|
All files                     |    66.67 |    41.67 |    53.33 |    64.44 |                |
 serverless-express           |    68.18 |    41.67 |    57.14 |    65.85 |                |
  express.js                  |    52.94 |       25 |       40 |       50 |... 21,22,27,32 |
  handler.js                  |       40 |       25 |       25 |       40 |... 12,18,22,27 |
  index.js                    |      100 |       75 |      100 |      100 |              9 |
 serverless-express/src       |    33.33 |      100 |        0 |    33.33 |                |
  access_control_middleare.js |    33.33 |      100 |        0 |    33.33 |            2,3 |
 serverless-express/src/aws   |      100 |      100 |      100 |      100 |                |
  aws_middleware.js           |      100 |      100 |      100 |      100 |                |
------------------------------|----------|----------|----------|----------|----------------|
Test Suites: 3 failed, 3 total
Tests:       7 failed, 9 passed, 16 total
Snapshots:   0 total
Time:        1.972s, estimated 2s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-express@2.0.8 test: `jest --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-express@2.0.8 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by iliasbhal** [comment]
Hi @pcwinters, it's fixed. 
You just need to `npm install serverless-express` again.

<img width="590" alt="screen shot 2018-12-02 at 9 09 36 pm" src="https://user-images.githubusercontent.com/9442803/49349021-9a4b4c80-f676-11e8-9b82-468fad49aafd.png">
